---
# Tasks for installing Rust and Cargo

- name: Check if Rust is installed
  shell: command -v rustc
  register: rustc_exists
  ignore_errors: true
  changed_when: false

- name: Download rustup installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
    mode: '0755'
  when: rustc_exists.rc != 0

- name: Install Rust
  shell: /tmp/rustup.sh -y
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"
  when: rustc_exists.rc != 0

- name: Clean up rustup installer
  file:
    path: /tmp/rustup.sh
    state: absent
  when: rustc_exists.rc != 0

- name: Add Cargo bin to PATH in shell config
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export PATH="$HOME/.cargo/bin:$PATH"'
    state: present
  when: rustc_exists.rc != 0