---
- name: Setup Mac with Essential Applications
  hosts: localhost
  connection: local
  become: false
  
  roles:
    - { role: homebrew, tags: ['homebrew'] }
    - { role: mas, tags: ['mas'] }
    - { role: karabiner, tags: ['karabiner'] }
    - { role: macos, tags: ['macos'] }
    - { role: zsh, tags: ['zsh'] }
