---
# Tasks for installing NVM (Node Version Manager)

- name: Check if NVM is installed
  stat:
    path: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  register: nvm_installed

- name: Install NVM
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  when: not nvm_installed.stat.exists

- name: Install latest LTS Node.js version
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install --lts
  args:
    executable: /bin/bash
  when: nvm_installed.stat.exists or not nvm_installed.stat.exists